/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface": "#131413",
        "on-tertiary-container": "#0069a5",
        "on-error": "#690005",
        "surface-container-high": "#292a29",
        "surface-bright": "#393938",
        "on-primary": "#323200",
        "on-secondary": "#00391d",
        "inverse-primary": "#606200",
        "surface-tint": "#cbce1d",
        "inverse-on-surface": "#30312f",
        "on-tertiary": "#003354",
        "surface-dim": "#131413",
        "surface-container-low": "#1b1c1b",
        "surface-variant": "#343534",
        "on-surface": "#e4e2e0",
        "outline-variant": "#484834",
        "on-primary-fixed-variant": "#484a00",
        "surface-container": "#1f201f",
        "on-secondary-fixed-variant": "#00522c",
        "secondary-fixed-dim": "#4ae08d",
        "surface-container-lowest": "#0d0e0d",
        "tertiary-fixed": "#cee5ff",
        "secondary": "#4ae08d",
        "on-secondary-fixed": "#00210f",
        "on-tertiary-fixed": "#001d33",
        "primary-container": "#e7ea3e",
        "tertiary": "#ffffff",
        "outline": "#93927a",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#cee5ff",
        "on-primary-container": "#676800",
        "surface-container-highest": "#343534",
        "secondary-fixed": "#6bfda7",
        "tertiary-fixed-dim": "#97cbff",
        "secondary-container": "#00b86a",
        "background": "#131413",
        "inverse-surface": "#e4e2e0",
        "primary-fixed": "#e7ea3e",
        "on-primary-fixed": "#1c1d00",
        "on-background": "#e4e2e0",
        "primary": "#ffffff",
        "error-container": "#93000a",
        "primary-fixed-dim": "#cbce1d",
        "on-secondary-container": "#004122",
        "on-surface-variant": "#c9c8ae",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#004a77"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {},
      "fontFamily": {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
};